
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{
    imports = [
        # ./docker.nix
        # ./7zip.nix
    ];

    environment.systemPackages = [
        (pkgs.writeShellScriptBin "whatIsMyIp" ''
            ${pkgs.curl}/bin/curl http://httpbin.org/get \
            | ${pkgs.jq}/bin/jq --raw-output .origin
        '')
    ];

    services.cron = {
        enable = true;
        systemCronJobs = [
            "*/5 * * * *      root    date >> /tmp/cron.log"
            "*/2 * * * *      root    whatIsMyIp >> /tmp/cron.log"
        ];
    };

}

