
########################################################################
#                                                                      #
# DO NOT EDIT THIS FILE, ALL EDITS SHOULD BE DONE IN THE GIT REPO,     #
# PUSHED TO GITHUB AND PULLED HERE.                                    #
#                                                                      #
# LOCAL EDITS WILL BE OVERWRITTEN.                                     #
#                                                                      #
########################################################################

{ config, lib, pkgs, ... }:

{
    environment.systemPackages = [
        (pkgs.writeShellScriptBin "update-nixos-configuration" ''
            echo start
            cd /etc/nixos
            echo 1
            if [ ! -d .git ]; then
                echo 2
                ${pkgs.git}/bin/git init .
                echo 3
                ${pkgs.git}/bin/git remote add origin "https://github.com/${(import ./settings.nix).github_repository}"
            fi
            echo 4
            ${pkgs.git}/bin/git fetch
                echo 5
            if [[ $(${pkgs.git}/bin/git rev-parse HEAD) != $(${pkgs.git}/bin/git rev-parse @{u}) ]]; then
                echo 6
                ${pkgs.git}/bin/git reset --hard HEAD
                echo 7
                ${pkgs.git}/bin/git checkout --force --track origin/master  # Force to overwrite local files
                echo 8
                ${pkgs.git}/bin/git pull --rebase
                echo "git finished"
                nixos-rebuild switch --upgrade
                echo "rebuild finished"
            fi
        '')
    ];

    services.cron = {
        enable = true;
        systemCronJobs = [
            "*/1 * * * *      root    update-nixos-configuration >> /tmp/update-nixos-configuration.log"
        ];
    };

}

